// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: delete_feed_follow.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteFeedFollow = `-- name: DeleteFeedFollow :execrows
DELETE FROM feed_follows WHERE id = $1
`

func (q *Queries) DeleteFeedFollow(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFeedFollow, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
